# Generated by Django 4.2.3 on 2024-01-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_id',
        ),
    ]
