# Generated by Django 4.2.3 on 2024-01-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_product_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.PositiveIntegerField()),
                ('buy_date', models.DateField()),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
