# Generated by Django 4.2.3 on 2024-01-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='discribe',
            field=models.TextField(),
        ),
    ]
