# Generated by Django 4.2.3 on 2024-01-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_memory_discribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(choices=[('G', 'GROUP'), ('S', 'MYSELF')], max_length=1),
        ),
    ]
