# Generated by Django 4.2.3 on 2024-07-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_product_remove_purches_ref_user_delete_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
