# Generated by Django 4.2.3 on 2024-07-23 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 5, 19, 12, 509381, tzinfo=datetime.timezone.utc)),
        ),
    ]
