# Generated by Django 4.2.3 on 2024-07-23 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 11, 58, 15, 57142)),
        ),
    ]
