# Generated by Django 4.2.3 on 2024-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(),
        ),
    ]
