# Generated by Django 4.2.3 on 2024-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_profile_about_alter_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('Bill', 'BILL MANAGER'), ('Rent', 'RENT MANAGER'), ('Clean', 'CLEANING MANAGER'), ('Grocery', 'GROCERY MANAGER')], default='Member', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
