# Generated by Django 4.2.3 on 2024-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_profile_about_profile_dept_profile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
